name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.1

  docs:
    name: Build docs and check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: pandoc/actions/setup@v1
    - uses: actions/setup-python@v6
      with:
        # Keep in sync with .readthedocs.yaml
        python-version-file: .python-version
    - name: Install plantuml
      run: |
        sudo apt install plantuml
    - name: Setup cached uv
      uses: hynek/setup-cached-uv@v2
    - name: Create venv and install docs dependencies
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        uv pip install --group=docs
    - name: Build HTML and check links
      run: |
        uv run make html
        uv run make linkcheck
      working-directory: docs/
